config/routes.rb
Rails.application.routes.draw do

  root "posts#index"
  resources :posts do

  	resources :comments

  end	

  
  
  # the resources :post above generates 7 other roots as below:
  # POST   /posts(.:format)          posts#create
 # new_post GET    /posts/new(.:format)      posts#new
# edit_post GET    /posts/:id/edit(.:format) posts#edit
     # post GET    /posts/:id(.:format)      posts#show
          # PATCH  /posts/:id(.:format)      posts#update
          # PUT    /posts/:id(.:format)      posts#update
          # DELETE /posts/:id(.:format)      posts#destroy
end

app/models/comment.rb
class Comment < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base #.all, .find(1) comes from AR::Base

	has_many :comments
	

# validate is an action (=method)
	validates  :title, presence: true, uniqueness: true
	validates :body, length: { minimum: 100 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

before_action :find_post, only: [:new, :create, :edit, :update]

  def new
  	# @post = Post.find(params[:post_id])
  	@comment = @post.comments.new
  end

  def show

  end	

  def create
  	# @post = Post.find(params[:post_id])
  	@comment = @post.comments.new(comment_params)

  	if @comment.save
  		flash[:success] = "Thanks for leaving a comment"
  		redirect_to post_path(@post)

  	else
  		flash[:error] = "Oops, something went wrong. Please try again"
  		render :new	
  	end	

  end	
  
  def edit  	
    @comment = @post.comments.find(params[:id])

  end

  def update
    @comment = @post.comments.find(params[:id])

    if @comment.update(comment_params)
      flash[:success] = "Thanks for updating your comment"
      redirect_to post_path(@post)

    else
      flash[:error] = "Oops, something went wrong. Please try again"
      render :edit 
    end 
    
  end  

  private

  def comment_params
  	params.require(:comment).permit(:body)
  end

  def find_post
  	@post = Post.find(params[:post_id])
  end	

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

# use the pre-defined method before_action below to use the method find_post defined at the bottom of the file across the file

# we use ':' before the name of the method below because that's the way  the method before_action works, like the method render used further down. But it cannot be generalised.
before_action :find_post, except: [:index, :new, :create]
  # def defines any method (or action in ruby), e.g. the def index end defines a new action index which is defined by the code between def index and end
  def index
    # ActiveRecord gives us queries like Post.all. See app/models/post.rb
    
    if params[:featured].present? and params[:featured] == "true"
      # GET all the posts from the posts table in the DB
  	 @posts = Post.where(is_featured: true).order("created_at DESC")
    else
      # .order("created_at DESC") allows the posts be shown from the latest posted post
     @posts = Post.order("created_at DESC")
    end

    if params[:published].present? and params[:published] == "true"
     @posts = Post.where(is_published: true).order("created_at DESC")
    else
     @posts = Post.order("created_at DESC")
    end

   

  end

  def show
    # GET post with the id from the URL

  	# @post = Post.find(params[:id])
    @comments = @post.comments


  end	

  def new
# The new form gets submitted to the create action
    @post = Post.new
  
  end

  def create
    @post = Post.new(post_params) #we populate the empty row with whatever comes from the methods (or actions) post_params which is defined at the bottom of this file 


    if @post.save
      flash[:success] = "Thanks for posting!"
      redirect_to root_path
    else 
      flash[:error] = "Oops, something went wrong! Please try again."
      render :new
    end 

  end	
  	
  def edit
# The edit form gets submitted to the update action

    # @post = Post.find(params[:id])
  
  end	
  
  def update

    # @post = Post.find(params[:id])
    if @post.update(post_params)
      flash[:success] = "Updated! \"#{@post.title}\"."

      redirect_to post_path(@post)
    else
      flash[:error] = "Try again!"
      render :edit
    end  
  end	

  def destroy

    # @post = Post.find(params[:id])
    @post.destroy
    redirect_to root_path
  end	
  
  	# private allows us to define methods (or actions) that are valid only within this file 
  private #private doesn;t need end

    def post_params
      # allow attributes that I trust, ignore any scary malicious unsation evil data

      params.require(:post).permit(:title, :body, :is_published, :is_featured)
    end  

    # To avoid repeating @post = Post.find(params[:id]) on several lines above we define the method below
  def find_post
    @post = Post.find(params[:id])
  end     
   
  			
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/edit.html.erb
<h1>Editing comment on "<%= @post.title %>"</h1>

<%= simple_form_for @comment, url: post_comment_path do |f| %>

	<%= f.input :body %>

	<%= f.button :submit %>

<% end %>	

app/views/comments/new.html.erb
<h1>Comment for <%= @post.title %></h1>

<%= simple_form_for @comment, url: post_comments_path do |f| %>

	<%= f.input :body %>

	<%= f.button :submit %>

<% end %>	

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Geopost</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>


	<header>
		<%= link_to "Home", root_path %>
		<%= link_to "Tell us a story", new_post_path %>
		<%= link_to "Recent", root_path %>
		<%= link_to "Featured", root_path(featured: true) %>
		<%= link_to "Published", root_path(published: true) %>




	</header>	

	<% flash.each do |key, value| %>	

		<div class="<%= key %>">
			<p><%= value %></p>
		</div>
			
	<% end %>

	<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= simple_form_for @post do |form| %>

	<%= form.input :title %>
	<%= form.input :body %>
	<%= form.input :is_published %>
	<%= form.input :is_featured %>

	<div class="btn">
		<%= form.button :submit %>

	</div>


<% end %>

app/views/posts/edit.html.erb
<h2>Edit</h2>


<%= render "form" %>

app/views/posts/index.html.erb
<section class="posts">
	<% @posts.each do |post| %>
	
		<div class="post">

			<h2><%= link_to post.title, post_path(post) %></h2>

			<p><%= truncate post.body, length: 20 %></p>
			<p>Posted <%= time_ago_in_words post.created_at %> ago.</p>

		</div>	

	<% end -%>
</section>

app/views/posts/new.html.erb
<h2>New</h2>

<%= render "form" %>

app/views/posts/show.html.erb
<div class="post">

	<h1><%= @post.title %></h1>
	<!-- If we just write <h1>blablabla</h1> it is static writing in between <%= %> allows it to be dynamic and use ruby -->
	<!-- <p><%= @post.body %></p> -->
	<%= simple_format @post.body %>
	<p>
	Posted <%= time_ago_in_words @post.created_at %> ago. 
	</p>
	<div class="actions">
		<%= link_to "Edit", edit_post_path(@post) %>
		<%= link_to "Delete", post_path(@post), method: :delete %>
		<%= link_to "Add a Comment", new_post_comment_path(@post) %>
	</div>
</div>

<div class="comments">
	<% @comments.each do |comment| %>
	<div class="comment">

		<%= simple_format comment.body %>
		<p>Left <%= time_ago_in_words comment.created_at %> ago. </p>
		<%= link_to "Edit", edit_post_comment_path(@post, comment) %>
	</div>	
	<% end %>	
</div>